// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab3.Data;

#nullable disable

namespace lab3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab3.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Skincare"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Makeup"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Haircare"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fragrance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suncare"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Body Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sets"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Men's Care"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kids Care"
                        });
                });

            modelBuilder.Entity("lab3.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2006, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tasnim@mail.com",
                            Name = "Tasnim",
                            Phone = "010001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2005, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah@mail.com",
                            Name = "Sarah",
                            Phone = "010002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2004, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali@mail.com",
                            Name = "Ali",
                            Phone = "010003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila@mail.com",
                            Name = "Laila",
                            Phone = "010004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hossam@mail.com",
                            Name = "Hossam",
                            Phone = "010005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1998, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nada@mail.com",
                            Name = "Nada",
                            Phone = "010006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1999, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@mail.com",
                            Name = "Youssef",
                            Phone = "010007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2001, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dina@mail.com",
                            Name = "Dina",
                            Phone = "010008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2003, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@mail.com",
                            Name = "Mona",
                            Phone = "010009"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2004, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled@mail.com",
                            Name = "Khaled",
                            Phone = "010010"
                        });
                });

            modelBuilder.Entity("lab3.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 150m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 280m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 200m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 100m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 500m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            OrderDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 80m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            OrderDate = new DateTime(2024, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 120m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            OrderDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 90m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 9,
                            OrderDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 250m
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            OrderDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 200m
                        });
                });

            modelBuilder.Entity("lab3.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Price = 100m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 3,
                            Price = 200m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 4,
                            Price = 80m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 5,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 2,
                            Price = 100m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 10,
                            Price = 500m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 7,
                            Price = 80m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 8,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 6,
                            Price = 90m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 9,
                            Price = 250m,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 3,
                            Price = 200m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("lab3.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Cleanser",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Toner",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Foundation",
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Lipstick",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Shampoo",
                            Price = 120m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Name = "Perfume",
                            Price = 300m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Name = "Sunscreen",
                            Price = 90m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Name = "Body Lotion",
                            Price = 110m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Name = "Brush Set",
                            Price = 250m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            Name = "Gift Box",
                            Price = 500m
                        });
                });

            modelBuilder.Entity("lab3.Entities.Order", b =>
                {
                    b.HasOne("lab3.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("lab3.Entities.OrderItem", b =>
                {
                    b.HasOne("lab3.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab3.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("lab3.Entities.Product", b =>
                {
                    b.HasOne("lab3.Entities.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("lab3.Entities.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("lab3.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("lab3.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("lab3.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
